customhost = "employee.cmndfr2xrbbf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "keesengpong-employee"
customregion = "us-east-1"
